### PR TITLE
Fixed search for single enum value in PostgreSQL

### LINKED ISSUE #180: Postgresql migrations endlessly tries to create enums
We have PostgreSQL table state like:
```sql
create table logs
(
    ...,
    target      varchar(7)
        constraint logs_target_enum_62e2522d7df9c
            check ((target)::text = 'catalog'::text)
);
```

but `cycle:migrate` can't detect that field already have enum type and each next migration tries to fix it in next way:
```php
class OrmDefault561cd35f5d5487d642a5bd8b65997299 extends Migration
{
    public function up(): void
    {        
        $this->table('logs')
            ->alterColumn('target', 'enum', [
                'nullable' => true,
                'default'  => null,
                'values'   => [
                    'catalog'
                ]
            ])
            ->update();
    }

    public function down(): void
    {
        $this->table('logs')
            ->alterColumn('target', 'string', [
                'nullable' => true,
                'default'  => null,
                'size'     => 7
            ])
            ->update();
    }
}
```

As I can see migrator can't understand that field already have enum functionality based on constraints

### PR DESCRIPTION
**Pull request by msmakouz**
Closes: #180

### CODE REVIEW

File: src/Driver/Postgres/Schema/PostgresColumn.php [hunk 1]
```diff
@@ -707,6 +707,13 @@ private static function resolveConstrains(
                 $column->enumValues = $enumValues;
                 $column->constrainName = $constraint['conname'];
                 $column->constrained = true;
+            } else {
+                $pattern = '/CHECK \\(\\(\\([A-Za-z]+\\)::(.+) = \'([A-Za-z]+)\'::(.+)\\)\\)/i';
```
Comment (roxblnfk) [inline src/Driver/Postgres/Schema/PostgresColumn.php]: that pattern should be moved in a const or a helper and unittested a lot

**Review by roxblnfk — APPROVED** [review]
